// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// STAGING Firebase project options.
///
/// This file currently contains the Firebase config that was previously in
/// `lib/firebase_options.dart`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjtEFfuUAdF7blmHm9k-z_P63L0bN3GSo',
    appId: '1:766335706711:web:aa1ab9c695932fc9b06512',
    messagingSenderId: '766335706711',
    projectId: 'cutline-526aa',
    authDomain: 'cutline-526aa.firebaseapp.com',
    databaseURL: 'https://cutline-526aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cutline-526aa.firebasestorage.app',
    measurementId: 'G-ZJQZ9Z5F0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKc37zt5h-CS6hBCMFJv0x1Ip3uwf9B1c',
    appId: '1:766335706711:android:c7a128ae2fed9130b06512',
    messagingSenderId: '766335706711',
    projectId: 'cutline-526aa',
    databaseURL: 'https://cutline-526aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cutline-526aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlyGRKfoAQ8ddfKJ-2XXqyYfmAdKmW83U',
    appId: '1:766335706711:ios:7674d1e5fd5f615db06512',
    messagingSenderId: '766335706711',
    projectId: 'cutline-526aa',
    databaseURL: 'https://cutline-526aa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cutline-526aa.firebasestorage.app',
    iosBundleId: 'com.cutline.staging',
  );

}