// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PROD Firebase project options.
///
/// Replace this file by running:
/// `flutterfire configure --project <prod-project-id> --out lib/firebase_options.dart`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ZsxnVvW0_Fql4U0fy_KjSym6OQmaOAA',
    appId: '1:266702152062:web:44c709c855047de811532f',
    messagingSenderId: '266702152062',
    projectId: 'cutline-prod-a55b9',
    authDomain: 'cutline-prod-a55b9.firebaseapp.com',
    storageBucket: 'cutline-prod-a55b9.firebasestorage.app',
    measurementId: 'G-CX2ELDM3JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBXhRAKU2b5CTYhilmKYEnXIH2hymXZk',
    appId: '1:266702152062:android:8581052ff35fbd2d11532f',
    messagingSenderId: '266702152062',
    projectId: 'cutline-prod-a55b9',
    storageBucket: 'cutline-prod-a55b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: 'com.cutline.prod',
  );
}