// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjtEFfuUAdF7blmHm9k-z_P63L0bN3GSo',
    appId: '1:766335706711:web:aa1ab9c695932fc9b06512',
    messagingSenderId: '766335706711',
    projectId: 'cutline-526aa',
    authDomain: 'cutline-526aa.firebaseapp.com',
    storageBucket: 'cutline-526aa.firebasestorage.app',
    measurementId: 'G-ZJQZ9Z5F0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKc37zt5h-CS6hBCMFJv0x1Ip3uwf9B1c',
    appId: '1:766335706711:android:c677e50e1d598778b06512',
    messagingSenderId: '766335706711',
    projectId: 'cutline-526aa',
    storageBucket: 'cutline-526aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEpcayJJCL8rOaV5M8wO49cZqC40gsuM',
    appId: '1:766335706711:ios:89abe79810720f1cb06512',
    messagingSenderId: '766335706711',
    projectId: 'cutline-526aa',
    storageBucket: 'cutline-526aa.firebasestorage.app',
    iosBundleId: 'com.example.cutline',
  );
}
