// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// DEV Firebase project options.
///
/// Replace this file by running:
/// `flutterfire configure --project <dev-project-id> --out lib/firebase_options_dev.dart`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC44a4TLt-NsGmT3XG3PBcxS4TF4VocfXM',
    appId: '1:725476828136:web:8fda3fc6a28c12197aba5d',
    messagingSenderId: '725476828136',
    projectId: 'cutline-dev',
    authDomain: 'cutline-dev.firebaseapp.com',
    storageBucket: 'cutline-dev.firebasestorage.app',
    measurementId: 'G-5TPGWB1K0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYH5CrI2g3nNe2wxxJIsVib4L_3GD_5Q',
    appId: '1:725476828136:android:e3893a3bfac815737aba5d',
    messagingSenderId: '725476828136',
    projectId: 'cutline-dev',
    storageBucket: 'cutline-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: 'com.cutline.dev',
  );
}